<?php

namespace notesBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdJoinedToCategory($noteId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT n, c FROM notesBundle:Note n
                JOIN n.category c
                WHERE n.id = :id'
            )->setParameter('id', $noteId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getNotesInCategory($limit)
    {
      $qb = $this->createQueryBuilder('n');

      // On fait une jointure avec l'entité Category avec pour alias « cat »
      $qb
        ->join('n.category', 'cat')
        ->addSelect('cat')
      ;

      // Puis on ne retourne que $limit résultats
      $qb->setMaxResults($limit);

      // Enfin, on retourne le résultat
      return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
